### ISSUE TITLE
No problem, just wanted to say thanks!

### ISSUE THREAD

**Issue by manderso7** [boredazfcuk/docker-icloud_photos_downloader#4]
I really appreciate you putting this together. It allows me to download my pictures to my local nas automatically and I've been wanting to make sure I wasn't locked in to another photo web service again.
Thanks again!

**Comment by boredazfcuk** [comment]
Thanks.

It's really not me that deserves the credit though. Plenty of people who are way more talented than me made this possible.

All I did was figure out how to work around a couple of bugs and package it as a container. The other guys are the real heroes.
